// RESPONSIVE
export const WINDOW_RESIZE = 'WINDOW_RESIZE';

// APP
export const APP_SET_TIP_TEXT = 'APP_SET_TIP_TEXT';
export const APP_SET_TIP_TARGET = 'APP_SET_TIP_TARGET';

// NAVBAR
export const NAVBAR_TOGGLE_MENU = 'NAVBAR_TOGGLE_MENU';
export const NAVBAR_SET_TITLE = 'NAVBAR_SET_TITLE';

// CATEGORIES
export const CATEGORIES_QUERY_UPDATE = 'CATEGORIES_QUERY_UPDATE';
export const CATEGORIES_SET_LOADING = 'CATEGORIES_SET_LOADING';
export const CATEGORIES_UPDATE = 'CATEGORIES_UPDATE';
export const CATEGORIES_SET_ACTIVE = 'CATEGORIES_SET_ACTIVE';

// POSTS
export const POSTS_QUERY_UPDATE = 'POSTS_QUERY_UPDATE';
export const POSTS_SET_LOADING = 'POSTS_SET_LOADING';
export const POSTS_UPDATE = 'POSTS_UPDATE';
export const POSTS_SET_ACTIVE = 'POSTS_SET_ACTIVE';

// POST
export const POST_SET_LOADING = 'POST_SET_LOADING';
export const POST_UPDATE_DATA = 'POST_UPDATE_DATA';
export const POST_UPDATE_COMMENTS = 'POST_UPDATE_COMMENTS';
export const POST_COMMENTS_UPDATE_SORT_CRITERION = 'POST_COMMENTS_UPDATE_SORT_CRITERION';
export const POST_COMMENTS_UPDATE_SORT_DIRECTION = 'POST_COMMENTS_UPDATE_SORT_DIRECION';
export const POST_TOGGLE_SHOW_FULL = 'POST_TOGGLE_SHOW_FULL';
export const POST_EMPTY = 'POST_EMPTY';
export const POST_SET_CREATING = 'POST_SET_CREATING';
export const POST_UPDATE_CATEGORY_SUGGESTIONS = 'POST_UPDATE_CATEGORY_SUGGESTIONS';
export const POST_CATEGORIES_SET_TIMEOUT = 'POST_CATEGORIES_SET_TIMEOUT';

// USER
export const USER_SET_LOGGED_IN = 'USER_SET_LOGGED_IN';
export const USER_UPDATE_DATA = 'USER_UPDATE_DATA';
export const USER_SET_LOGIN_ACTIVE = 'USER_SET_LOGIN_ACTIVE';
export const USER_SELECT_LOGIN_FORM = 'USER_SELECT_LOGIN_FORM';
export const USER_SET_LOADING = 'USER_SET_LOADING';
export const USER_UPDATE_VOTES = 'USER_UPDATE_VOTES';
export const USER_ADD_POST = 'USER_ADD_POST';

// PROFILE
export const PROFILE_SET_USERNAME = 'PROFILE_SET_USERNAME';
export const PROFILE_SET_LOADING = 'PROFILE_SET_LOADING';
export const PROFILE_UPDATE_DATA = 'PROFILE_UPDATE_DATA';
export const PROFILE_SET_PREVIEW_ACTIVE = 'PROFILE_SET_PREVIEW_ACTIVE';
export const PROFILE_UPDATE_ACTIVITY = 'PROFILE_UPDATE_ACTIVITY';
export const PROFILE_POSTS_UPDATE_SORT_CRITERION = 'PROFILE_POSTS_UPDATE_SORT_CRITERION';
export const PROFILE_POSTS_UPDATE_SORT_DIRECTION = 'PROFILE_POSTS_UPDATE_SORT_DIRECTION';
export const PROFILE_COMMENTS_UPDATE_SORT_CRITERION = 'PROFILE_COMMENTS_UPDATE_SORT_CRITERION';
export const PROFILE_COMMENTS_UPDATE_SORT_DIRECTION = 'PROFILE_COMMENTS_UPDATE_SORT_DIRECTION';
export const PROFILE_RESET = 'PROFILE_RESET';

// SEARCH
export const SEARCH_FILTER_UPDATE = 'SEARCH_FILTER_UPDATE';
export const SEARCH_SET_TIMEOUT = 'SEARCH_SET_TIMEOUT';
export const SEARCH_UPDATE_SORT_CRITERION = 'SEARCH_UPDATE_SORT_CRITERION';
export const SEARCH_UPDATE_SORT_DIRECTION = 'SEARCH_UPDATE_SORT_DIRECTION';

// RESET
export const RESET = 'RESET';
