// RESPONSIVE
export const WINDOW_RESIZE = 'WINDOW_RESIZE';

// NAVBAR
export const NAVBAR_TOGGLE_MENU = 'NAVBAR_TOGGLE_MENU';
export const NAVBAR_SET_TITLE = 'NAVBAR_SET_TITLE';

// CATEGORIES
export const CATEGORIES_QUERY_UPDATE = 'CATEGORIES_QUERY_UPDATE';
export const CATEGORIES_SET_LOADING = 'CATEGORIES_SET_LOADING';
export const CATEGORIES_UPDATE = 'CATEGORIES_UPDATE';
export const CATEGORIES_SET_ACTIVE = 'CATEGORIES_SET_ACTIVE';

// POSTS
export const POSTS_QUERY_UPDATE = 'POSTS_QUERY_UPDATE';
export const POSTS_SET_LOADING = 'POSTS_SET_LOADING';
export const POSTS_UPDATE = 'POSTS_UPDATE';
export const POSTS_SET_ACTIVE = 'POSTS_SET_ACTIVE';

// USER
export const USER_SET_LOGGED_IN = 'USER_SET_LOGGED_IN';
export const USER_UPDATE_DATA = 'USER_UPDATE_DATA';

// SEARCH
export const SEARCH_FILTER_UPDATE = 'SEARCH_FILTER_UPDATE';
export const SEARCH_SET_TIMEOUT = 'SEARCH_SET_TIMEOUT';

// RESET
export const RESET = 'RESET';
